### ISSUE TITLE
http://localhost:3000/api/token returns a key without permission

### ISSUE THREAD

**Issue by Greykoil** [Developer-Autodesk/workflow-node.js-view.and.data.api#6]
The access token that is being returned from api/token does not have the required permissions to view my model. 
Trying to load it results in a 
No access
 Sorry. You don’t have the required privileges to access this item.
 Please contact the author.

**Comment by Greykoil** [comment]
I solved this by adding the following scope to credentials.js
scope: 'data:read data:write bucket:create data:create bucket:read'

**Comment by leefsmp** [comment]
We haven't yet had time to migrate our complete sample codebase. For viewing you would logically only need a 'data:read' token. I wrote the following blogpost on generating your OAuth  tokens: [Landing your Forge OAuth authentication workflow](http://adndevblog.typepad.com/cloud_and_mobile/2016/07/landing-your-forge-oauth-authentication-workflow.html).

By sending a token with such privileges to your client app, you basically provide an open door to all your data and account to any user of the website ... so strongly discouraged, I suppose.
