### ISSUE TITLE
Error with npm

### ISSUE THREAD

**Issue by bigdoods** [Developer-Autodesk/workflow-node.js-view.and.data.api#8]
Hi,

I have just tried to run this project locally on a machine with ubuntu 16.04 OS using nodejs v3.6.1 . When i run `npm install` on the master branch it failed with the following errors:

npm ERR! Linux 4.4.0-34-generic
npm ERR! argv "/usr/bin/nodejs" "/usr/bin/npm" "install"
npm ERR! node v6.3.1
npm ERR! npm  v3.10.3
npm ERR! code EREADFILE
npm ERR! Error extracting /home/bigdoods/.npm/fs/0.0.0/package.tgz archive: ENOENT: no such file or directory, open '/home/bigdoods/.npm/fs/0.0.0/package.tgz'
npm ERR! 
npm ERR! If you need help, you may report this error at:
npm ERR!     https://github.com/npm/npm/issues
npm ERR! Please include the following file with any support request:
npm ERR!     /home/bigdoods/yano/models.autodesk.io/npm-debug.log

Here is the npm-debug
[npm-debug2.txt](https://github.com/Developer-Autodesk/workflow-node.js-view.and.data.api/files/436876/npm-debug2.txt)

It also doesnt deploy to heroku and the site at https://models.autodesk.io/ seems to be broken too. 

Cheers,

**Comment by autodesk-adn** [comment]
https://models.autodesk.io/ was fixed today - there was an issue in a recent update. My fault really

I am running Ubuntu 14.04.4 LTS, node.js 6.2.1, npm 3.9.3, and have no issue on this sample - at least for what you described above. Do you got a permission issue on the folder you want to install?

-cyrille
